### ISSUE TITLE
CT Output Description in Wiki

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#100]
I'm noticing that we don't describe any of the CT specific output fields in Trips_CTTruck.csv in the wiki.  I'm currently looking for an explanation of the codes in the "truckType" field, but really all the fieds should be explained.  

@rickdonnelly and @jfdman, can we please add a description of "Trips_CTTruck.csv" to the CT wiki page

**Comment by rickdonnelly** [comment]
I tried to update this sometime in the past, and it appeared to work. But when I look at wiki tonight it is not there. I've put on Dropbox [here](https://www.dropbox.com/s/xqfpscrtti067fs/ctmodel_outputs.md) (GitHub doesn't allow Markdown attachments here) and am sending it to @bstabler to ask him to help me stitch it in. (The problem must be on my end, but unless @bstabler can see what I'm doing wrong perhaps faster fix is for me to huddle with him.

**Comment by bstabler** [comment]
I posted Rick's file here - https://github.com/tlumip/tlumip/wiki/CT#outputs

**Comment by bettinardi** [comment]
This looks great
Just one extra detail - @rickdonnelly  - can we get the units for value, and I guess tons would be overkill, they are just american tons I assume.  But for value can we get if they are in dollars, or thousands, or millions... and what year dollars the output is in.

**Comment by bettinardi** [comment]
Sorry one more - is there any other context you can add about the difference between a TT and a CS.  It looks like the CS represents the most common semi configuration, but do the Feds have any additional context we can link to - ideally a page with pictures of what these types look like would be the best - if it's out there for us to link to...

**Comment by bettinardi** [comment]
Email from Rick -

"...I am 100 percent certain that the values in CT are in current U.S. dollars and the weights in tons (2,000 lbs = 1 ton, also sometimes referred to as short tons). The CFS data are reported in thousands of tons and millions of dollars, and therefore so is the FAF. When CT reads the FAF database it converts them into individual dollars and tons, for in older versions of Java we would occasionally hit an underflow exception when trying to divide a small fraction of thousand tons across several zones within each FAF area. After that initial conversion we never use millions or thousands of anything in the model."
