### ISSUE TITLE
VIZ DB builder should run all TS years first using the user defined number of threads

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#101]
When using the following properties:
viz.max.concurrent.ts = 4
viz.max.concurrent.total = 12

The current code set is not properly completing the TS years first.  It seems to somewhat randomly choose to work on a given year within the maximums specified.  

The java code related to launching the VIZ DB process is here:
https://github.com/tlumip/tlumip/blob/master/src/java/com/pb/tlumip/ao/VizDbBuilder.java#L119 

For context the following property file configurations have been tried with the following run times.  In all configurations we have found that TS years are not assigned first (the properly file configuration above is short hand as 4,12):
4, 12 = 3 hours 10 mins
6, 13 = 2 hours 50 mins
6, 18 = 2 hours 40 mins
11,11 = 3 hours 20 mins
12, 14 = 3 hours 30 mins
12, 22 - 2 hours 40 mins
12, 40 = 2 hours 50 mins 
(note that the speed tests were completed on a machine with 16 processors.  the 12,40 likely would have worked if the number of processors didn't cap the speed).  

In a standard SWIM run there are 32 years that need to be complied, 11 of those 32 are TS.
For reference in reviewing results, TS years are every third year;
20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50

For further context, the reason why we want all TS years to run first is because the new machines ODOT has have 128 GBs of RAM.  These machines are now capable to process all TS years at once.  A TS year takes about 1.25 hours to complete.  If they can be run at once the full process should be shortened to about 1.5-1.75 hours.  If they run in two-three phases, then the processing time ~doubles / triples.

**Comment by bstabler** [comment]
From reviewing the log file, it looks like the order of years for the viz db build processes is random and therefore we can’t force it to do all the TS ones first.  I think we’ll need to update the code.

**Comment by bettinardi** [comment]
First off, let's remember issue #52 and if we can just build a separate AO monitor that runs Viz DB builders in the background as each year finishes - that would be the best solution.  If that can't be done, my new favorite way to address this would to not leave it up to an algorithm to determine what years to build in what order.  I would like to update tsteps so that the VIZ column can be coded with 1s, 2s, 3s...  The software would only build the database for years tagged (it would not longer search out which years should be built) and it would build years based on user input.  Say 8 years were tagged as 1, it would launch those years and build those 8 years at the same time, then move to the 2s then the 3s...

Or something similar if the team can come up with an improved approach.  In summary - 
 - the best option would be to run Viz DB builds in the background after each year completes, with a final assembly after the last year (likely requires breaking out year assembly from final assembly in tsteps).
 - the second best option is to give the user control on how the year "bundles" are assembled via tsteps.

**Comment by bettinardi** [comment]
We should also consider having TSTEPs functionality that both indicates which years to run DB creator on and which years to delete individual year DBs on.  I'm thinking of this, because as we push the base run year into the future, we might want to keep database summaries from "historic" years in the repo (in the outputs for previous historic years) and not have the process delete them.  So we should be able to specify in TSTEPS what years we want the database run for and what years should have the year specific databases deleted.
