### ISSUE TITLE
Move to Visum 18

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#102]
It looks like we will need to build (zip) a new set of python libraries to properly interface with Visum 18.  Visum 18 interfaces with matrices a little different than 16.  Some calls in SWIM_Visum_Main.py might need to get updated as well.

As context, here is the error:
09-Jan-2019 20:34, INFO, load csv file: D:/swim2/Ref25_0_01_18/inputs/parameters/inpZMXFileNames.csv
09-Jan-2019 20:34, INFO, ......read zmx file: demand_matrix_a_ampeak.zmx
09-Jan-2019 20:34, INFO, matrix 1 sum 2151654
09-Jan-2019 20:34, INFO, Traceback (most recent call last):
09-Jan-2019 20:34, INFO,   File "D:/swim2/Ref25_0_01_18/model/code/visum/SWIM_VISUM_Main.py", line 1628, in <module>
09-Jan-2019 20:34, INFO,     s.insertMatrixInVisum('auto and truck', start=hwyDemandMatrices[0], end=hwyDemandMatrices[1])
09-Jan-2019 20:34, INFO,   File "D:/swim2/Ref25_0_01_18/model/code/visum/SWIM_VISUM_Main.py", line 706, in insertMatrixInVisum
09-Jan-2019 20:34, INFO,     VisumHelpers.SetODMatrix(self.Visum, i+1, mat)
09-Jan-2019 20:34, INFO,   File "D:\swim2\model\lib\Python27\lib\site-packages\VisumPy\helpers.py", line 131, in SetODMatrix
09-Jan-2019 20:34, INFO,     matrix = __getODMatrix(Visum, which)
09-Jan-2019 20:34, INFO,   File "D:\swim2\model\lib\Python27\lib\site-packages\VisumPy\helpers.py", line 568, in __getODMatrix
09-Jan-2019 20:34, INFO,     matrix = Visum.Net.ODMatrices.ItemByKey(which)
09-Jan-2019 20:34, INFO,   File "D:\swim2\model\lib\Python27\lib\site-packages\win32com\client\dynamic.py", line 522, in __getattr__
09-Jan-2019 20:34, INFO,     raise AttributeError("%s.%s" % (self._username_, attr))
09-Jan-2019 20:34, INFO, AttributeError: <unknown>.ODMatrices
09-Jan-2019 20:34, ERROR, Errors occurred running run HIGHWAY_ASSIGNMENT

Here is the message I sent to PTV:
From Visum 16 to 18 the com calls for matrixes (like Visum.Net.ODMatrices) changed.
I am running into an issue with the Visum 16 version of VisumPy\helpers.py – example function below.

I’m not finding the new Visum 18 version of this installed with 18 – what folder should I be looking in.  I’m thinking my Visum install didn’t complete successfully.

def __getODMatrix(Visum, which):
    """Get an OD matrix from VISUM

    visum - COM object - the VISUM object
    which - string - demand segment code OR
          - number - matrix number

    return OD matrix

    matrix = __getODMatrix(Visum, 2)
    matrix = __getODMatrix(Visum, "C")
    """
    if __isNumberType(which):
        matrix = Visum.Net.ODMatrices.ItemByKey(which)
    else:
        dseg = Visum.Net.DemandSegments.ItemByKey(which)
        matrix = dseg.ODMatrix
    return matrix

**Comment by bettinardi** [comment]
I believe I found a hack to get this work - something close to a fix we just need to formalize it.

I copied the 13 files found here:
C:\Program Files\PTV Vision\PTV Visum 18\Exe\PythonModules\VisumPy

To here:
D:\swim2\model\lib\Python27\Lib\site-packages\VisumPy

@bstabler - maybe you can help QC this hotwire fix.  And if you think it is good enough, can you help me formalize this in the dependencies zip:
https://github.com/tlumip/tlumip/tree/master/root/model/lib

**Comment by bettinardi** [comment]
Let's not close this until #95 is also resolved

**Comment by bettinardi** [comment]
Let's not close this until #89  is also resolved

**Comment by bettinardi** [comment]
@nsdhakar here are the steps from above summarized again.  After I looked at the files I was going to send, I think these instructions cover it.  Let me know if you need any thing additional from me to get Visum 18 running:

1. Updated property pointer to Visum 18

2. I copied the 13 files found here:
C:\Program Files\PTV Vision\PTV Visum 18\Exe\PythonModules\VisumPy

To here:
D:\swim2\model\lib\Python27\Lib\site-packages\VisumPy

3. line 1145 and 1148 in SWIM_VISUM_Main.py removed Skim from AddSkimMatrix

**Comment by nsdhakar** [comment]
Followed @bettinardi instructions using the existing SWIM setup and was able to run it successfully all the way to the end.

**Comment by nsdhakar** [comment]
@bettinardi: as I have successfully run the VISUM 18 setup at my end, I am thinking to update the repository for the same. Should I update the master or you would like to have a new visum 18 branch?

**Comment by bettinardi** [comment]
Update the master please and I will test.
I'm hoping that issue #89 can be resolved shortly after this issue, as I would like to be running the latest version of SWIM / Visum with issue #89 resolved (it's one of my higher priorities).

Thanks

**Comment by nsdhakar** [comment]
@bettinardi: I have updated the master for Visum 18 and Java 8. Please test. We can close the issue once you have tested and verified. Now I am working on the VOT issue.
