### ISSUE TITLE
Update count data and plots in swimr

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#103]
We would like to update swim with some current counts.  This is done through count locations in Visum.  It looks like the viz db will scrape any additions up from the "output" file countlocations.csv.  So we should be good to add new AAWDT fields to the count locations and have them added to the database, However, we would like support to verify that the current fields are not hard coded, and if we add count years / fields they will make it into the csv and then into the database.

Assuming we can get additional years of count data into the database, we would like to verify that the swim function - "plot_traffic_count" - will automatically scrape up additional years of data, or if we need to update that function to use additional years of data.

Similarly, this plot was put in as kind of a place hold - only reviewing a small handful count locations.  We would like support to call this function multiple times, or improve this function to look across our ~200 ATR locations and plot them all.  Given that this would be a lot of lines, we could envision that the plots my be grouped by volume or area of the state.

**Comment by bstabler** [comment]
Maybe I'm confused, but it doesn't matter since the table is the same in each year and that's why there is only one in the all years DB?  Regardless, it is the first folder processed according to the dir() call:

https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/viz/all_Viz_DB.R#L32

**Comment by bettinardi** [comment]
It matters because we will have 3 or so Visum networks for any given scenario.  SI pulls the count table from the Visum network and places it in the outputs folder.  If I don't remember (not do I want to try and remember) to keep the count table consistent in every Visum file, then the counts table will be different in different output years.  I want to know which version file I need to update the counts in to get it into the Viz database.  It's still not clear to me from the code which is used.  Please clairfy which output year makes it into the Viz database for the three tables that don't change by year.  Again I want to update the user guide with this extra context on those three tables:
https://github.com/tlumip/tlumip/wiki/SWIM-VIZ#viz-db-tables

Please consider adding the answer to the user guide.

**Comment by bstabler** [comment]
Ok.  So, if the table can change by year, then it should be stored by year.  How about we update the script to store the count table by year?

**Comment by bettinardi** [comment]
Disagree - it's base year data we only need one year.  Differing years just allows for easier management of the system.  Having a multi year file for base year data would make this worse.  
I just need to know what year the base year data is pulling from.  Ideally it would be a year I could specify.

**Comment by bettinardi** [comment]
Results of my testing so far -
 - I was able to code new count data into VIsum (still looking for clarity from @bstabler on which version file needs the correct count data input)
 - SWIM ran, populated the count locations csv files with the updated count data.  
 - The Viz DB ran and populated with all the new data in the count tables.
 - swimr does not automatically pick up new count data in the function - plot_traffic_count.  

I will need support from @bstabler and @landisrm to help dig into plot_traffic_count and see how it is getting the count data from the VIZ DB and see if it can be made more generic (flexible) to allow new fields to be added without code / package updates.  We also need to review plot_countcomparison to verify that it will work with different years.  I'm intending to test it with a 2016 test, but have not yet setup the data for that test.

**Comment by bettinardi** [comment]
Forgot to add - that I did successfully update the markdown template to use plot_traffic_count to plot a new set of count locations and multiple plots - so that works.  The note will be that we will want to refine that markdown template before we finalize #95

**Comment by landisrm** [comment]
@bettinardi , here is the relevant code from `plot_traffic_count`.  So instead of these hard coded years, you would like it to find all columns of the form AAWDT_YYYY and simply plot all the years represented?

```
plot_traffic_count <- function(db, atr = c("01-001", "01-011", "01-012")){



  counts <- dplyr::tbl(db, "COUNTLOCATIONS") %>%
    dplyr::select(
      ANODE = FROMNODENO, BNODE = TONODENO, ATR_NUM,
      `2000` = AAWDT_2000, `2005` = AAWDT_2005, `2010` = AAWDT_2010,
      `2015` = AAWDT_2015
    ) %>%
```

**Comment by bettinardi** [comment]
Correct - thanks again
