### ISSUE TITLE
Update Transit Fare Instructions on Wiki

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#105]
@bstabler will update the wiki page on transit fares to include information on how to properly align (setup) the transit service area used by the generalized transit approach and the fare districts.
https://github.com/tlumip/tlumip/wiki/Transit-Assignment#fares

**Comment by bstabler** [comment]
I significantly cleaned-up the [Transit Assignment](https://github.com/tlumip/tlumip/wiki/Transit-Assignment) page, please review.  Thanks.

**Comment by bettinardi** [comment]
Some questions after reviewing the new page:
https://github.com/tlumip/tlumip/wiki/Transit-Assignment#los-info - you should define P2E the first time it is used on the page.

https://github.com/tlumip/tlumip/wiki/Transit-Assignment#assignment-and-skimming - the following is never a good idea to write.  Now you need to explain why it should not be changed - what is it - "2. Assignment time interval is set to 0 to 24 and should not be changed."

"These do not sum to daily since they represent just one peak (am or pm?) " - I believe the answer is AM, but you should check with Joel.

https://github.com/tlumip/tlumip/wiki/Transit-Assignment#fares - what's the NA value, is it the 999999 from above - I'm not tracking, please make this clearer.

https://github.com/tlumip/tlumip/wiki/Transit-Assignment#adjust-sdt-and-ltf-skims - I'm not tracking why LDT is skipped from this discussion.  If it's not included, why are we skimming it...  I think it's just that the language in this paragraph is not very clear.

Those are comments that need to get cleaned up just from a readabilty standpoint.  From an "answer my question" stand point, I'm still unclear with how the fare skims are generated for LTF.  The LTF Bus skim text links the reader down to the fares section, but then the question is never answered.  Please make it clearer for how the full fare matrices are determined.  Just saying that they are unrelated / non consistent with the LOS info is not enough explanation,

**Comment by bstabler** [comment]
I think we can now close this issue.
