### ISSUE TITLE
Remove world market input file that's not used.

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#107]
The following file is identified in the properties file and is found in the parameters folder (ActivityConstraintsIWorldMarkets.csv):
https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/globalTemplate.properties#L642

However, looking through the code seems to verify that this file is never used (the data that is used is actually stored in the POI list 7 -World Markets - in the Visum input file.

The file should be removed from the repo and the reference in the properties file should be deleted (the row removed).

**Comment by bettinardi** [comment]
@jfdman - I just did a test where I commented out the following line - 
https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/globalTemplate.properties#L702

PT hung right at the beginning (hasn't crashed, but Java hasn't moved forward from this line):

22-Nov-2019 22:41, INFO, Number of people who listed no occupation, no index 2507397
22-Nov-2019 22:41, INFO, CommandFile Path: D:/swim2/SWIM25_Issue107/model/config
22-Nov-2019 22:41, INFO, Cmd File: D:\swim2\SWIM25_Issue107\model\config\commandFile.txt
22-Nov-2019 22:41, INFO, Command file has been found
22-Nov-2019 22:41, INFO, DoneFile Path: D:/swim2/SWIM25_Issue107/model/config/zzptdaf_done.txt
22-Nov-2019 22:41, INFO, Deleting the zzptdaf_done.txt file
22-Nov-2019 22:41, INFO, Starting nodes, cluster and application.  Waiting 15000 ms for nodes to start
22-Nov-2019 22:41, INFO, Writing 'StartNode' to command file
22-Nov-2019 22:42, INFO, Writing 'StartCluster' to command file
22-Nov-2019 22:42, INFO, Writing 'StartApplication' to command file
22-Nov-2019 22:42, INFO, Wait here for the application to finish

Can you let me know if PT uses that file or any idea why this would have hung...

**Comment by bstabler** [comment]
I looked in the tlumip code, the pasaat_swim code, and the tlumip python code and I can't any references to `si.activityconstraintsi.worldmarkets`.  Are you sure PT hung because of this change?

**Comment by bettinardi** [comment]
I'll do another test to confirm
