### ISSUE TITLE
Move Cost Assumptions in Visum Assignment Parameters to Properties file

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#112]
It has become clear that ODOT will likely need the option to update value of time and vehicle operating cost assumptions on a semi-regular basis, and for things like future scenarios (as MPGs go up and drivers switch to EVs, per mile costs are expected to drop, similarly new tax structures could increase per mile costs).

Right now operating costs and value of time assumptions are embedded in a static xlm parameter file for use with Visum.  We need to update the code to use a property file to update a network user attribute fields in Visum which will then be used to calculate impedance values in the generalize cost calculations for assignment.

**Comment by jeabraham** [comment]
We need to check the transport cost coefficients in AA as well, for goods movements we usually have a composite cost function based on time and distance.  For personal movements we should be getting the logsum from the travel model, so if you change the coefficients in Visum it should automatically flow through into AA through the skim file. 

Let’s check this when we’re doing our update in June/July.

--
John Abraham
jea@hbaspecto.com
403-232-1060

**Comment by bettinardi** [comment]
A reminder that we intended to look at this when we were digging into AA, 

I also wanted to capture that the AOC component of the calculation (for personal vehicles) should likely come straight from this parameter already defined.
https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/globalTemplate.properties#L135

So we still will need to add parameters for value of time values specific to assignment, but we should make sure we are thinking about parameters and inputs already defined (like in PT and AA) and how to use those as opposed to just specifying possibly duplicate user parameters for TA.

**Comment by bettinardi** [comment]
I think the easiest solution to this is to put truck and auto AOC and VOT assumptions into a "Network" level user attribute into Visum, as opposed to buried in the procedure files (saved outside of Visum).  That will make them much easier to interface with.

**Comment by bettinardi** [comment]
A reminder to myself - I believe I have a solution worked out and I have updated the wiki accordingly.  However, I don't want to fully push this forward until we have SWIM 2.6 functional in Visum 2020. 

Here are notes to myself as to where I kept my work:
\\s6000e\6420only\Statewide\Tools\SWIM\SWIM_26\ModelBuild\03_Network\_VOT_AOC

https://github.com/tlumip/tlumip/wiki/Traffic-Assignment#link-impedance
