### ISSUE TITLE
swimr legend issue

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#121]
The map legends don’t update when you switch between showing absolute difference versus percent difference

**Comment by bettinardi** [comment]
WOC 7 summary - 
In #111 I noted that it would be ideal for the templates to be reviewed after their location is updated.  This is related.  Issue #111 should be resolved first, then a review and cleaning of know issues should be made.  Although I believe this issue is a function issue as opposed to a template issue, so it may be slightly different there.

**Comment by landisrm** [comment]
I think this post shows how to do it.  https://gis.stackexchange.com/a/301516/169725
