### ISSUE TITLE
Modernize SWIM linkages to Census Industry and Occupation codes

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#125]
SWIM maps the occupation and industry codes used with the various SWIM steps to census PUMS tables (specifically the INDP and OCCP person fields).  This linkage is completed in the files [acs_occupation_2005_2009.csv](https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/parameters/acs_occupation_2005_2009.csv) and [pums_to_split_industry.csv](https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/parameters/pums_to_split_industry.csv), both are located under “inputs\parameters”.  The team has noted that there is no clear history, instructions, or documentation on how these files were created.  In recent updates the lack of documentation created an issue where the team needed to make judgement calls on how to update the acs occupation crosswalk for the latest census years / product.  The team anticipates that this will become a larger problem as newer census products are released such as the 2020 census product.  This issue is to create documentation (likely a wiki page) for instructions on how to generate/develop these two files, and then an updated set of inputs following the developed instruction set.

It should also be noted that the current PopSim file – [acs_occupation_2005_2009_forPopSim.csv](https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/parameters/acs_occupation_2005_2009_forPopSim.csv) – retained the 2005_2009 year naming, which is not correct (this file is used for the 2013-2017 census product).  The team should think about what the naming for these files looks like, and where/how the meta data on the census products used in SWIM should be kept / documented.

**Comment by bettinardi** [comment]
Additional context from a reply from Joel:
The file https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/parameters/acs_occupation_2005_2009_forPopSim.csv is used to code the PECAS broad occupation category from the PUMS occupation. It should be checked to make sure that the codes are correct. It was recently updated with new codes for ACS occupations in the 2013 to 2017 PUMS data as part of the SWIM PopulationSim implementation. The PECAS occupation categories for missing ACS occupation categories were interpolated from existing ACS categories. This may not be 100% accurate.

**Comment by bstabler** [comment]
from @jeabraham.  

  - [Occupations revised.xlsx](https://github.com/tlumip/tlumip/files/6690213/Occupations.revised.xlsx)
  - [Occupations coding for PI-PECAS_with_occp_commodity_xtab.xlsx](https://github.com/tlumip/tlumip/files/6690214/Occupations.coding.for.PI-PECAS_with_occp_commodity_xtab.xlsx)
  - [Oregon Design Diagram Draft 8.xlsx](https://github.com/tlumip/tlumip/files/6690215/Oregon.Design.Diagram.Draft.8.xlsx)
  - [IndustryOccupationSplitIndustryCorrespondence_new.xlsx](https://github.com/tlumip/tlumip/files/6690217/IndustryOccupationSplitIndustryCorrespondence_new.xlsx)

The design diagram draft 8 shows which occupation categories A1 through D4 were used to split each industry. In a lot of cases A through C are office, while D is production, but not always.  For example, you can see that in retail, where it’s split, just A and B are office, and C is production. And Education is completely different, with teachers of course being in production facilities (not offices) even though they are in professionals in category B.

It looks like the file IndustryOccupationSplitIndustryCorrespondence_new.xlxs is consistent with the design diagram, but it does have more information.  For example, it shows that when occupation D1 is in "Manufacturing-High Tech”, 44.275% goes to MFG_htec_LI which uses light industrial space, and the remainder 55.725% goes to MFG_htec_HI which uses heavy industry space. I haven’t done a detailed comparison of IndustryOccupationSplitIndustryCorrespondence_new.xlxs against the design diagram. If you think you need to use IndustryOccupationSplitIndustryCorrespondence_new.xlxs we should do the detailed comparison against the design diagram, or figure out its pedigree. 

Also attached is the detailed workbook "Occupations revised.xlsx" defining all the A1 through D4 occupations. From this you should be able to fill in any holes in the occupations. Note there is a sheet “Occ Codes” which is a full accounting of the 2002 and 2008 PUMS occupations codes. If there are brand new occupations that occur, you need to use the definitions in the tab “Summary (13 as used)” as occupation detailed codes within a 2 digit SOC code were assigned to one of two categories depending on the mean years of education.   (I don’t think any brand new OCCP codes showed up. But, if any did, you might have to calculate the mean years of education within the PUMS observations to assign it to B3 vs B4, C1 vs C2, C3 vs C4, or D3 vs D4). 

I’ve also attached “Occupations coding for PI-PECAS_with_occp_commodity_xtab.xlsx”.

I haven’t yet found the INDP to unsplit industry coding.  Do you have it?  My understanding is that you have it, that you have no problem with the INDP part of this.  Maybe you already had the OCCP part of it too.  The part that you were missing, as I understand it, is which occupation codes were related to which split portions. That is in the “Oregon Design Diagram Draft 8.xlsx” file.

**Comment by bstabler** [comment]
We discussed this issue on the SWIM call and here's our plan for when we tackle this issue in the next phase of work:
  - We need to build a crosswalk from PUMS INDP and PUMS OCCP to PECAS Industry (the unique set from the industry field in the IndustryOccupationSplitIndustryCorrespondence_new.xlsx file) and PECAS occupation (the H, I columns in the Code sheet in Occupations revised.xlsx).
  -  We're going to do this using the latest PUMS data and we're going to script it.
  -  We'll need to review some more of the details in these files, such as the Summary (13 as used) tab in the Occupations coding for PI-PECAS_with_occp_commodity_xtab.xlsx file and also talk with HBA about the assumptions, factors, etc. that are part of the process.  We may want to simplify the SWIM/PECAS understanding of occupation + industry since it's not very adaptable to updates in PUMS data (which is used for population synthesis).  
  -  We'll test this by running all of SWIM, including SPG (PopSim) and PECAS.
  - We'll likely need to fix issues to get SWIM working and make adjustments / "calibrate" the model with the updated process to create occupation + industry coding.

The goal is a repeatable process to take PUMS data and create PECAS inputs (and PopSim inputs to feed the PECAS model).  We'll also document the process.

**Comment by goreaditya** [comment]
Population related files in commit e6abf8f5bc2288615f9b9b8ab4913f754cbbdf86

**Comment by goreaditya** [comment]
AA related updates in commit - 6ec0f6c55643c58b3d8c5293e5b703ae6e72b8a3

**Comment by bettinardi** [comment]
resolved
