### ISSUE TITLE
Unused columns in activityconstraintsi

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#127]
We believe that the 30 columns in activityconstraintsi that are currently populated with zeros by the code are not actually needed by AA, see columns here:  https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/SWIM_VISUM_Main.py#L143

The first test to see if this issue can be resolved is to remove these columns and see if AA still runs correctly.

**Comment by bettinardi** [comment]
Correction from above - the activityconstraintsi file is actually a flat file and does not have specific columns for each activity, so the intent is the same, but the test is actually above removing all the rows that reference the 30 zero'd out activities as opposed to removing columns.

**Comment by bettinardi** [comment]
From Graham:

The model will still run. The thing to confirm is that it's still doing the same thing, and not putting importers and exporters inside the region - i.e. there shouldn't be nonzero entries in ActivityLocations for importers and exporters inside the region.

**Comment by AzrgExplorers** [comment]
I've run a scenario without those zero entries, and it's identical to the one with the zero entries. No importers or exporters inside the region. So we can safely remove these entries.

**Comment by graham97** [comment]
I've run a scenario without those zero entries, and it's identical to the one with the zero entries. No importers or exporters inside the region. So we can safely remove these entries.

**Comment by bettinardi** [comment]
WOC 7 Summary - 

This Task needs to edit SWIM_VISUM_Main such that activityconstraintsi.csv is no longer exported with the 30 zero activities identified in the first comment.  This means removing several sections of code and then testing, See ~500 to 550 (in addition to defined fields at 143):

https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/SWIM_VISUM_Main.py#L505

These fields should not exist in Visum, but we will want to verify that and remove any fields that can be removed.

**Comment by goreaditya** [comment]
The following activities ignored by AA model were removed from [ActivityConstraintsI.csv]() file:
```
accommodations_expt
accommodations_impt
communications_and_utilities_expt
communications_and_utilities_impt
construction_expt
construction_impt
education_reports_to_sponsors_expt
education_reports_to_sponsors_impt
energy_expt
energy_impt
entertainment_services_expt
entertainment_services_impt
fire_business_and_professional_services_expt
fire_business_and_professional_services_impt
food_services_expt
food_services_impt
government_administration_expt
government_administration_impt
health_services_expt
health_services_impt
higher_education_expt
higher_education_impt
personal_and_other_services_and_amusements_expt
personal_and_other_services_and_amusements_impt
retail_trade_expt
retail_trade_impt
transport_expt
transport_impt
wholesale_trade_expt
wholesale_trade_impt
```

**Comment by bettinardi** [comment]
I'm noticing that this the information in the comment above is no longer built into ActivityConstraintsI.  However, I'm also noticing that all internal zone information has also been cut (this was a ~10MB output file, now it's only world zones (6000 series) and 20 kb).  When did that occur, was that a separate issue?  Did we mean for that to occur

**Comment by bettinardi** [comment]
@nsdhakar - please see question in the comment above.  If we can resolve that question I think we can close this issue.

**Comment by bettinardi** [comment]
As best as I can tell this issue is fully resolved and I am now closing
