### ISSUE TITLE
add AA source code to tlumip GitHub 

### ISSUE THREAD

**Issue by bstabler** [tlumip/tlumip#130]

**Comment by bettinardi** [comment]
WOC 7 summary - 
Obtain AA source code and add it to the TLUMIP repo

**Comment by bstabler** [comment]
Will be at https://github.com/tlumip/AA

**Comment by bstabler** [comment]
I believe this is now done.  @bettinardi?

**Comment by bettinardi** [comment]
You are much better suited to make the call on this (source code is not my area of expertise).  So I trust your assessment that this issue is done and will mark close and complete.
