### ISSUE TITLE
Update PT Cost Coefficients

### ISSUE THREAD

**Issue by jfdman** [tlumip/tlumip#60]
PT cost coefficients are more negative than would be suggested by prevailing best practices. Typically work values of time are 1/2 of the average hourly wage rate, and non-work values of time are 1/3 - 1/4 of the average hourly wage rate. The values of time in the tour mode choice models are about 1/2 that. This is likely due to low estimated VOTs. Suggest that we assert cost coefficients to match prevailing best practice values of time (leaving in-vehicle times alone).  Also check code that sets income segment to be consistent with income ranges (0-30k, 30-60k, 60k+).

**Comment by jfdman** [comment]
Check with Metro on VOTs used in the Metro models. Also check highway assignment VOTS

**Comment by RAKnudson** [comment]
Joel will update PT cost coefficents.  Alex will run base year and review swimr html results for trip length and VMT (also count comparison).

**Comment by jfdman** [comment]
I have updated VOTs based on average hh income within each income bin/2080 (hours per year) * (0.5 if mandatory or 0.33 if non-mandatory)

**Comment by jfdman** [comment]
[pt mode choice parameter revisions.xlsx](https://github.com/tlumip/tlumip/files/2947934/pt.mode.choice.parameter.revisions.xlsx)
