### ISSUE TITLE
Remove unnecessary alpha2beta.csv fields

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#71]
There are a handful of legacy zone fields that are solely being kept because there were defined in the alpha2beta.csv.  Before they are cleared, we need to review the model components that use alpha2beta.csv and verify that the structure of alpha2beta.csv can be altered and that no processes within SWIM use the fields that are marked for deletion.  The fields to be deleted are:

AREATYPE
COUNTYFIPS
GRIDACRES (Can AreaSQFT be calculated by Visum and not be a field for the user to populate...)
HPMS
MPOCALIBRATIONZONES
NORTHCOLUMBIA
PUMA1990
STATEFIPS

This would leave the following fields in alpha2beta.csv (can we reorder):

BZONE
PECASNAME (does PECAS actually use this, can this be dropped)
ALDREGION
PUMA2000
HOURPARK
DAYPARK
LUINTENSITYCODE (how is this used..., maybe we can drop this too.)
MPOMODELEDZONES
ACT
FARE
STATE
COUNTY

Related question - what process pulls in / uses "ServiceArea" - I don't see it identified in "zoneFieldNames.csv"  Note that all this cleaning is related to issue #70 as well.

**Comment by bettinardi** [comment]
Test confirms that AZONE, NOTES, and DESCRIPTION Field can be deleted.  Move external station description to Visum "NAME" field.

**Comment by bettinardi** [comment]
Is FARE still used - it looks legacy

**Comment by bettinardi** [comment]
Note to self to verify that the AZONE, NOTES, and DESCRIPTION fields have been successfully removed from the repo version files before closing this ticket. (I have a feeling that this is going to be a messy tracking process, and those fields might creep back in).

**Comment by bettinardi** [comment]
Just posted new version files with AZONE, NOTES, and DESCRIPTION removed

**Comment by bettinardi** [comment]
We should test if BZONE can be removed.  From:  https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/SWIM_VISUM_Main.py
It looks as if BZONE really comes from "MAINZONENO" (which is the better way to handle it).  So we might be able to remove that field (I will try and do a test).

**Comment by jfdman** [comment]
Update wiki after modifying inputs

**Comment by bettinardi** [comment]
I'm going to do some tests in early July to see what work remains and better scope what issues remain for issues 70 and 71

**Comment by bettinardi** [comment]
@jeabraham - can I confirm that AA needs (or assumes it will receive)  STATEFIPS and COUNTYFIPS.  In my testing it seems that AA crashes without these fields - does that sound right?

**Comment by bettinardi** [comment]
@jfdman and @bstabler, I'm trying to run some tests to understand this issue.  PT keeps hanging when I remove certain fields from alpha2beta.csv.  Is there a way to quickly identify what fields PT assumes exist in alpha2beta, or better yet - which fields it uses in it's process / calculations?

**Comment by graham97** [comment]
> @jeabraham - can I confirm that AA needs (or assumes it will receive) STATEFIPS and COUNTYFIPS. In my testing it seems that AA crashes without these fields - does that sound right?

AA does indeed need STATEFIPS and COUNTYFIPS in alpha2beta, but I think we could take this out. All it does with those fields is combine them into a FIPS field in the FloorspaceZonesI file. It looks like the FIPS field used to be used for county-level output summaries, but the code that does that is no longer referenced anywhere.

I'd like to get John's confirmation (when he gets back next week) before we do the code change necessary for this.

**Comment by bettinardi** [comment]
Thank you Graham.  I would appreciate the effort to remove these fields from AA (if easy / possible), but an option B I'm considering is keeping them in alpha2beta but having them built in Python off of the State and County fields that we maintain.  I haven't been maintaining the FIPS fields, so it's dangerous.  And those no reason to have a user maintain both a character name and a numeric reference - so I think we can just build in a python conversion step to build FIPS fields if needed.

The context is that other SWIM modules might use these fields too, so I think we might keep the fields anyway (even if they are removed from AA).

**Comment by bettinardi** [comment]
Things learned to-date.  I have learned that the following fields can be dropped without any apparent issue:

**Comment by jfdman** [comment]
The following properties are listed in the properties file:

alpha2beta.file                                       = @ROOT.DIR@/@SCENARIO.NAME@/@SCENARIO.OUTPUTS@/t@CURRENT.INTERVAL@/alpha2beta.csv
alpha.name                                            = Azone
beta.name                                             = Bzone
pumaField.name                                        = PUMA2000
stateLabelField.name                                  = State
stateFipsField.name                                   = STATEFIPS

I have searched through PT and found the following fields are used:
the fields referred to in the properties file as alpha,name and beta.name
DayPark
HourPark
Azone

I don't see any other references to fields in the file in PT. But there is a class called ZoneMap in com.pb.tlumip.model that uses GridAcres and LUIntensity. The class was created by Rick Donnelly in 2004. I think it was for the commercial vehicle model. It is instantiated in com.pb.tlumip.et.EIModel defineModel() method but that method appears to be deprecated? I don't know what this code is for so I am going to have to defer to others. There is also a main() method in ZoneMap so maybe it is being called from AO? Maybe this is enough info for Ben or someone else to figure it out?

**Comment by bstabler** [comment]
- remove fields we know we can
  - add dynamic FIPS coding
  - @bettinardi remove fields for ALD not used
  - can we remove PECASNAME; is it needed by AA?

**Comment by goreaditya** [comment]
The following table displays the variables that are active (needed by model to run) in alpha2beta.csv file.
| Variable Names      | Variable Active | Location                                                     |
| ------------------- | --------------- | ------------------------------------------------------------ |
| AREATYPE            | No              | -                                                            |
| COUNTYFIPS          | Yes             | -  https://github.com/tlumip/AA/blob/7e2f1bc563307247b5a11e98a43b086c2270ce78/swim2/src/com/hbaspecto/oregon/pecas/aa/OregonAAPProcessor.java#L343      - https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/root/scenario/model/code/ALD_Inputs.R#L117      -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/pi/OregonPIPProcessor.java#L138 |
| GRIDACRES           | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/model/ZoneMap.java#L72      -  https://github.com/tlumip/pasaat_swim/blob/e54f0177cb22f09e5509cefb4af46c10c953a89e/src/java/com/pb/models/pt/TazManager.java#L182 |
| HPMS                | No              | -                                                            |
| MPOCALIBRATIONZONES | No              | -                                                            |
| NORTHCOLUMBIA       | No              | -                                                            |
| PUMA1990            | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/root/scenario/model/code/ALD_Inputs.R#L117 |
| STATEFIPS           | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/pi/OregonPIPProcessor.java#L137      - https://github.com/tlumip/AA/blob/7e2f1bc563307247b5a11e98a43b086c2270ce78/swim2/src/com/hbaspecto/oregon/pecas/aa/OregonAAPProcessor.java#L342      -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/root/scenario/model/code/ALD_Inputs.R#L117 |
| BZONE               | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/model/ZoneMap.java#L71 |
| PECASNAME           | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/pi/OregonPIPProcessor.java#L153      - https://github.com/tlumip/AA/blob/7e2f1bc563307247b5a11e98a43b086c2270ce78/swim2/src/com/hbaspecto/oregon/pecas/aa/OregonAAPProcessor.java#L358 |
| ALDREGION           | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/root/scenario/model/code/ALD_Inputs.R#L117 |
| PUMA2000            | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/root/scenario/model/code/ALD_Inputs.R#L117 |
| HOURPARK            | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/pt/TLUMIPTazManager.java#L51 |
| DAYPARK             | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/pt/TLUMIPTazManager.java#L50 |
| LUINTENSITYCODE     | No              | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/model/ZoneMap.java#L73 |
| MPOMODELEDZONES     | No              | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/epf/Calibration/EPF_LineGraphs.java#L112      - https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/ts/assign/Network.java#L2153 |
| ACT                 | No              | -                                                            |
| FARE                | No              | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/ts/assign/TransitAssignAndSkimManager.java#L1489 |
| STATE               | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/epf/Calibration/EPF_LineGraphs.java#L130      - https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/epf/Calibration/EPF_LineGraphs.java#L152      -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/root/scenario/model/code/ALD_Inputs.R#L117 |
| COUNTY              | Yes             | -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/epf/Calibration/EPF_LineGraphs.java#L131      - https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/src/java/com/pb/tlumip/epf/Calibration/EPF_LineGraphs.java#L153      -  https://github.com/tlumip/tlumip/blob/f15e64cedc72abc29fb1250da55ff545f47458f2/root/scenario/model/code/ALD_Inputs.R#L117 |

**Comment by bettinardi** [comment]
It looks like from the commits that grid acres is now automatically generated in the code - so I can remove that field from the inputs.  On 7-15-2020 Ben noted that CountyFIPS was going to be dynamically calculated / populated in the code, so the user didn't have to worry about that.  Did that occur, can I remove CountyFIPS?

In addition to those two user attribution fields I plan to remove, I also plan to remove the following, based on the notes above:
  - Areatype
  - HPMS
  - MPOCALIBRATIONZONES
  - NorthColumbia
  - LUintensity

Please confirm that I can remove these 5 and GridAcres and CountyFIPS for my test to close this issue.

@bstabler - the notes above from @goreaditya seem to indicate that I can also remove FARE.  The wiki suggests that FARE is still in use but the link within that comment is dead, so maybe the wiki is out of date.  Ben, can you review and confirm that FARE is no longer used as the wiki indicates - text from the wiki:

"If making transit fare changes, update the inputs\t0\IntraCityTransitFares.csv file. This file includes the district to district transit fares in year 2007 dollars and is used in conjunction with the Zone FARE district attribute to build a zone-to-zone fare matrix since fare is not skimmed from the network (see Fares)."

**Comment by bettinardi** [comment]
Great work - SWIM is looking so much cleaner
