### ISSUE TITLE
Update SWIM base year to 2016 (as a validation point, not a calibration)

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#75]
At this point, I propose that since we are in 2017, soon to be 2018 (at least in SWIM time soon), that we build a process so that years 2010-2015 in the swim model turn into static years, which we can use to re-seed 2016 on an infrequent basis.  And change the SWIM run setup to use t25 as the seed year, and t26 (2016) as the kick off year.  I see no since we won't change anything in those 2010-2016 years in any scenario, I see no reason to continually run those 6 years (burning a day of run time).  We just update the run process to start in t26...

Similarly, when we do this, we would likely want to update NED inputs (global insight outputs) to the most recent information and push out to 2050 if possible.

**Comment by bettinardi** [comment]
From today's call - I think we should try and approach this as a formalized update of tsteps for "start model at arbitrary point" (instead of just a failed model run).  I think one way to think about this is removing the "i" aspect from tsteps, and just having the model setup assume what is needed for the "i" aspects.

**Comment by bettinardi** [comment]
I think I figured out the way to configure tsteps to start at say 2020, assuming that 2009-2019 have been run successfully, in a "history" run.  So this is a good starting point, and maybe the setup could be improved a little bit, but I think this is almost resolved:

| Year | SI | NED | ALD | POPSIMSPG1 | AA | POPSIMSPG2 | PT | CT | TA | TR | PT - Logsums Only |
|------|----|-----|-----|------------|----|------------|----|----|----|----|-------------------|
| 19   | 1  | 1   |     |            |    |            |    |    |    |    |                   |
| 28   |    |     |     |            | i  |            |    |    |    |    |                   |
| 29   |    |     | i   | i          | 1  | i          | i  | i  | i  | i  | i                 |
| 30   | 1  | 1   | 1   | 1          | 1  |            |    |    |    |    |                   |
| 31   | 1  | 1   | 1   | 1          | 1  |            |    |    |    |    |                   |
| 32   | 1  | 1   | 1   | 1          | 1  | 1          | 1  | 1  | 1  | 1  | 1                 |

**Comment by bettinardi** [comment]
Still some testing with AA taking a long time in the first year of the re-run (2019), but I think this is really close to done:
https://github.com/tlumip/tlumip/tree/master/root/scenario/model/config

**Comment by bettinardi** [comment]
Summary for WOC 7 - 
This is an issue that will require some investigation budget.  ODOT has a TSTEP configuration they believe is correct to start a run in 2019/20 (off of a SWIM run from 2009-2019).  However, it does not seem to be properly restarting the run in 2019.  There seems to be an AA link back to the 2009 start year.  So some AO investigation is needed to understand what is not working correctly to restart the run, and what needs to be changed in AO to allow for a start off a a year that isn't 2009.

**Comment by bettinardi** [comment]
I came up with a potential solution using https://github.com/tlumip/tlumip/wiki/Helper-Scripts#runrestartr.   Need to discuss with the team and re-think what this task should cover.

**Comment by bstabler** [comment]
- @bettinardi describe the process in the wiki
  - we will try it out and suggest improvements, documentation updates

**Comment by bettinardi** [comment]
I put an initial draft of this process here -
https://github.com/tlumip/tlumip/wiki/Helper-Scripts#runfuturer

Maybe after we play and tweak it, we can put it in a more formal spot on the wiki

**Comment by nsdhakar** [comment]
The objective here is to save runtime by not running previous years but maintain the same data flow across years. Alex'x approach above is sufficient for that. Updated the t29FileCopy.R to include necessary files and automate paths. 

Here are steps to run for a new validation year:

1. Have a model run with outputs produced up to the validation year (ex. t26)
1. Setup a new scenario with the model and inputs folder. Run build_run.bat as it is.
2. Copy run_NewValYearFileCopy.R to scenarios folder. Next, update the script for "dataDir" (original run with historic runs up to the validation year) and "validationYear" (ex. 26) and run.
3. Copy RunFuture.R to scenarios folder. Next, update the script for "StartPoint" (the year following the validation year, ex. ""Starting SI in year 27") and run.
4. Run "run_model_Future.bat"
