### ISSUE TITLE
Low Fruit file clean-up

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#77]
In recent cleaning it was identified that the file(s) "Tours_SDT.csv" takes up about 5-10% of a total SWIM run.  As far as ODOT is aware, this file is never used.  We could get a significant storage savings by updating the process to delete this file at the close of every year.  "Patterns_SDT.csv" might be another candidate for deletion, however at this point the total savings would be closer to 1%, so the value of continiuing down the list of files (by size) past this point is likely not worth it.

**Comment by RAKnudson** [comment]
Better fix - update PT (or similar module) not to write-out files that have been marked (or not marked - Joel's decision) in the properties file.

**Comment by jfdman** [comment]
this should be done - test a properties file without tour file.

**Comment by bettinardi** [comment]
@jfdman - I just did a test where I commented out the following lines:
https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/globalTemplate.properties#L488
https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/globalTemplate.properties#L624

PT again hangs, just like it did under the SWIM 2.5 code (the test and message below is from the PopSim SWIM 2.6 code/ setup).

#### SWIM 2.6 error / hang:

23-Nov-2019 00:27, INFO, HHWorkerTask011, Sending HHs to results queue.
23-Nov-2019 00:27, INFO, HHWorkerTask04, Sending HHs to results queue.
23-Nov-2019 00:27, INFO, HHWorkerTask07, Sending HHs to results queue.
23-Nov-2019 00:27, INFO, HHWorkerTask09, Sending HHs to results queue.
23-Nov-2019 00:27, INFO, HHWorkerTask010, Sending HHs to results queue.
23-Nov-2019 00:28, INFO, HHWorkerTask08, Sending HHs to results queue.
23-Nov-2019 00:28, INFO, HHWorkerTask08, Received messageId=ProcessHouseholds message from=MSServerTask0
23-Nov-2019 00:28, INFO, HHWorkerTask08, Processing hh block 346
23-Nov-2019 00:28, INFO, HHWorkerTask08, Choosing LDT binary and patterns.
23-Nov-2019 00:28, INFO, Creating new LDT tours
23-Nov-2019 00:28, INFO, Created 710 LDT tours.
23-Nov-2019 00:28, INFO, HHWorkerTask08, Sending long distance tours  to the long distance worker.
23-Nov-2019 00:28, INFO, HHWorkerTask08, Running Short-distance travel models
23-Nov-2019 00:28, INFO, LongDistanceWorkerTask, Received messageId=HouseholdsProcessed message from=HHWorkerTask08 at Sat Nov 23 00:28:12 PST 2019
23-Nov-2019 00:29, INFO, HHWorkerTask08, Sending HHs to results queue.

### SWIM 2.5 error / hang point:

19-Nov-2019 18:50, INFO, HHWorkerTask012, Sending HHs to results queue.
19-Nov-2019 18:50, ERROR, Could not determine industry for person 2265398_3
19-Nov-2019 18:50, ERROR, Could not determine industry for person 2269165_1
19-Nov-2019 18:50, ERROR, Could not determine industry for person 2269546_1
19-Nov-2019 18:51, INFO, HHWorkerTask04, Sending HHs to results queue.
19-Nov-2019 18:51, INFO, HHWorkerTask04, Received messageId=ProcessHouseholds message from=MSServerTask0
19-Nov-2019 18:51, INFO, HHWorkerTask04, Processing hh block 511
19-Nov-2019 18:51, INFO, HHWorkerTask04, Choosing LDT binary and patterns.
19-Nov-2019 18:51, INFO, Creating new LDT tours
19-Nov-2019 18:51, INFO, Created 1414 LDT tours.
19-Nov-2019 18:51, INFO, HHWorkerTask04, Sending long distance tours  to the long distance worker.
19-Nov-2019 18:51, INFO, HHWorkerTask04, Running Short-distance travel models
19-Nov-2019 18:51, INFO, LongDistanceWorkerTask, Received messageId=HouseholdsProcessed message from=HHWorkerTask04 at Tue Nov 19 18:51:29 PST 2019
19-Nov-2019 18:52, INFO, HHWorkerTask04, Sending HHs to results queue.

**Can you please advise on what to test next**

**Comment by jfdman** [comment]
Try leaving in the property but removing the file name

**Comment by bettinardi** [comment]
Just to be sure I'm understanding the instruction - you are saying to test changing the following lines from:  
ldt.tours=@ROOT.DIR@/@SCENARIO.NAME@/@SCENARIO.OUTPUTS@/t@CURRENT.INTERVAL@/Tours_LDT.csv
and
sdt.person.tours=@ROOT.DIR@/@SCENARIO.NAME@/@SCENARIO.OUTPUTS@/t@CURRENT.INTERVAL@/Tours_SDT.csv

to 
ldt.tours=
and
sdt.person.tours=

https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/globalTemplate.properties#L488
https://github.com/tlumip/tlumip/blob/master/root/scenario/inputs/globalTemplate.properties#L624

**Comment by bettinardi** [comment]
I just did a test with:
ldt.tours=
and
sdt.person.tours=

And PT hung with the following message:
28-Jan-2020 15:38, INFO, HHWorkerTask08, Choosing LDT binary and patterns.
28-Jan-2020 15:38, INFO, Creating new LDT tours
28-Jan-2020 15:38, INFO, Created 693 LDT tours.
28-Jan-2020 15:38, INFO, HHWorkerTask08, Sending long distance tours  to the long distance worker.
28-Jan-2020 15:38, INFO, HHWorkerTask08, Running Short-distance travel models
28-Jan-2020 15:38, INFO, LongDistanceWorkerTask, Received messageId=HouseholdsProcessed message from=HHWorkerTask08 at Tue Jan 28 15:38:00 PST 2020
28-Jan-2020 15:38, INFO, HHWorkerTask011, Sending HHs to results queue.
28-Jan-2020 15:38, INFO, HHWorkerTask06, Sending HHs to results queue.
28-Jan-2020 15:38, INFO, HHWorkerTask04, Sending HHs to results queue.
28-Jan-2020 15:38, INFO, HHWorkerTask09, Sending HHs to results queue.
28-Jan-2020 15:38, INFO, HHWorkerTask08, Sending HHs to results queue.
28-Jan-2020 15:38, INFO, HHWorkerTask08, Received messageId=ProcessHouseholds message from=MSServerTask0
28-Jan-2020 15:38, INFO, HHWorkerTask08, Processing hh block 346
28-Jan-2020 15:38, INFO, HHWorkerTask08, Choosing LDT binary and patterns.
28-Jan-2020 15:38, INFO, Creating new LDT tours
28-Jan-2020 15:38, INFO, Created 707 LDT tours.
28-Jan-2020 15:38, INFO, HHWorkerTask08, Sending long distance tours  to the long distance worker.
28-Jan-2020 15:38, INFO, HHWorkerTask08, Running Short-distance travel models
28-Jan-2020 15:38, INFO, LongDistanceWorkerTask, Received messageId=HouseholdsProcessed message from=HHWorkerTask08 at Tue Jan 28 15:38:52 PST 2020
28-Jan-2020 15:39, INFO, HHWorkerTask08, Sending HHs to results queue.

**Comment by bstabler** [comment]
Maybe we need to update LDT as well since the code creates an LDT data writer on [line 89](https://github.com/tlumip/pasaat_swim/blob/master/src/java/com/pb/models/pt/ldt/LDTDataWriter.java#L89) based on the `ldt.tours` token?
