### ISSUE TITLE
swimR Update instructions

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#81]
A handful of errors have been identified in the swimR functions (specifically the inconsistent treatment of calculating the percent difference for tables like pop, employment and VMT - VMT seems to incorrectly reference the base year, while Pop and Employment) correct reference the comparison scenario year).

Additionally, enhancements need to be added to swimR - for example MPO pop/emp level projections need to be added as a base comparison each time SWIM / swimR is run. (It would also be great if we could setup swimR to automatically generate at the end of every run - since we will always want to see it).

To accomplish these items, we need instructions on issuing new instances of swimR so that the agency can own and feel empowered to update swimR as needed.

**Comment by bettinardi** [comment]
In recent zone editing it became clear that we need a way to update the zone layer in swimr

**Comment by bstabler** [comment]
To begin, I added notes on how to get started - https://github.com/tlumip/swimr#getting-started

**Comment by bettinardi** [comment]
The current solution has a swimr package "developer" change the zone system being used within swimr.  We need an option for either the swimr package to dynamically determine which zone system is in the input database(s) or have a user input to the swimr reference and compare knit templates to have a point to the specific zone system to use for a given comparison.

Currently, ODOT needs to maintain the SWIM 2.5 zone structure for day-to-day analysis, but wants to test swimr in SWIM 2.6 development, which has a revised zone structure.  The permanent solution will need to account for this type of use.

**Comment by bettinardi** [comment]
The outstanding issues are being captured in a string of issues leading with "swimr"
