### ISSUE TITLE
Remove internal calculation of connector travel speeds

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#82]
The team embedded the automated calculation (overwriting) of connector travel speeds.  The SWIM software should not calculate this (as we don't always want a uniform speed methodology applied over the entire network), the user guide should inform users to populate this connector attribute.

**Comment by nsdhakar** [comment]
Alex, I found the connector travel speed calculations in two xml files: [ initAutoAssignment.xml](https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/initAutoAssignment.xml) and [pathBasedAssignmentSettings_Full.xml](https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/pathBasedAssignmentSettings_Full.xml). I have updated them to remove the procedures of calculating connector travel time for auto and trucks 
I couldn't test the model yet as I don't have the input version file. I will send you an email regarding that.
