### ISSUE TITLE
Understand Select Link Error

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#85]
The select link for the Woodburn external model is throwing a set of errors (year t50, scenario "NewZones"):

  | count | value | mod
-- | -- | -- | --
2295-2281 | 23 | 0.451833 | 1
2295-2281 | 23 | 0.548199 | 1
904-2295 | 29 | 0.203138 | 4
353-2457 | 1 | 0.451584 | 1
353-2457 | 2 | 0.220416 | 2
353-2457 | 1 | 0.107584 | 1

To help prompt ODOT's memory this work is stored at:
\\s6000e\6420only\Statewide\Tools\SWIM\SWIM_2_5\ModelApplication\ExternalModels\Woodburn

We need to trace the select link results creation and issues and understand what this error table is telling us, if anything.

**Comment by bettinardi** [comment]
As additional context - I think the issue in the table above is that you have zone pairs like 904-2295 that shares an end in the model. The code must be trying to verify that all paths to a given set of zones can be accounted for.   Since one end is in the model, all paths to and from that model must be in the model somewhere.  We should track down if these are issues and build a better issue reporter that is embedded in the select link processor and not the urban model external model code (where it resides currently).  If there is an issue we should know when the select link ends, and not when the urban external model is running.

The error checking code can be seen between lines 460-491 at:
https://github.com/RSGInc/SOABM/blob/master/template/scripts/externalModel_SWIM.r

**Comment by nsdhakar** [comment]
Here is an update on this issue:

Added a similar process (a new python script) into the SL module itself. The SL properties file is also updated include the new python script name and its output file name. The output of the process are OD pairs that do not have SL percent sum up to 100%. Those OD pairs need to be reviewed to make sure that there are no issues with the SL process. The wiki is updated to reflect this change.

**Comment by bettinardi** [comment]
I think the setup is working really well.  Just one issue - it seems like "sl_review.csv" generate empty if there are no problems.  Is it possible to update so that if there are no issues "sl_review.csv" does not generate?

Additionally, it would be great if a message could be written to the run log that indicated brought it to the users attention that there were issues in the sl_review.csv file.
