### ISSUE TITLE
Truck assignment costs reevaulation

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#89]
Recent work with SWIM has revealed that the "TRUCK_COST" calculation in SWIM is likely not correct.  It uses the same value of time assumptions as auto:
Floor(144*[TOLL_PRTSYS(D)]+17.28*[LENGTH])

Note from Peter Bosa's latest email regarding why truck tolls were coded as less than auto in the value pricing scenarios - 

"The truck Value of Time is much higher than auto Value of Time. This leads to lower *perceived* time equivalent costs of the toll rates, even if the monetary value of the toll rates are higher for trucks than autos. The table below demonstrates this concept:"

Value of   time (congestion pricing) within Metro Kate model | SOV   & HOV | Heavy   and Medium Trucks
-- | -- | --
Peak   Period | | 
| Value of   time - 2017$   (current year) | $21.62/hr | $43.75/hr
Minutes   of perceived time per $ | 3.11 | 1.54
Off-peak   Period | | 
 | Value of   time - 2017$   (current year) | $14.38/hr | $43.75/hr
Minutes   of perceived time per $ | 4.68 | 1.54

**Comment by jfdman** [comment]
Alex will post the VOTs to use and Ben will implement.

**Comment by bettinardi** [comment]
Adding the context to surrounding the table above (just as an FYI):

The Value of Time assumptions are default values in the latest version of the Metro regional travel demand model (Kate).  Value of time (VOT) is segmented by vehicle type as shown in Table 2 (the table in the comment above). The Metro travel demand model will apply equivalent time value of proposed toll rates to apply the equivalent delay (or time penalty) incurred, as appropriate for each pricing concept.  The TOM model will further refine these assumptions to reflect a distribution for value of time.

* Heavy trucks are assumed to have a toll price roughly equivalent to 1.93 times Medium Truck based on assumption that truck tolls will be applied per axle.

**Comment by nsdhakar** [comment]
Alex, I found the truck cost calculation procedure in two xml files: [initAutoAssignment.xml](https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/initAutoAssignment.xml) and [pathBasedAssignmentSettings_Full.xml](https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/pathBasedAssignmentSettings_Full.xml). 

Floor(144*[TOLL_PRTSYS(D)]+17.28*[LENGTH])

The values in the equation are calculated as per [link impedances](https://github.com/tlumip/tlumip/wiki/Traffic-Assignment#link-impedance). We are currently using 25$/hr for both auto and truck.

**Comment by nsdhakar** [comment]
We recognize benefits of having different VOTs for peak and off-peak periods. Off-peak periods contains more mix of activities therefore, the value of time is generally lower than the peak periods where most of the mandatory activities happen.

However, for now, we will keep only one VOT for each mode (auto and truck). We will use the peak period VOTs from the table above (Metro VOT). 

If needed, we may implement VOTs by peak and off-peak in future.

**Comment by jfdman** [comment]
$21.62 (2017) = $19.29 (2010)
$14.38 (2017) = $12.83 (2010)
$43.75 (2017) = $39.04 (2010)

**Comment by nsdhakar** [comment]
@bettinardi: looking back at meeting notes from 06/15/2018 - "Rick posted a literature review of Truck VOTs with average recommended VOT ($39/hr). Close to Metro VOT ($43/hr)". So we still want to use Metro VOT of 43.75 $hr as decided before? (see the comment before Joel's)

[Cost Overview](https://github.com/tlumip/tlumip/wiki/Costs-Overview#2010-cost-assumptions) page says that the costs are in 2009 dollars. Is that right? if yes then I would need a CPI to convert 2017 value to 2009. Joel provided the values in 2010 dollar.

**Comment by bettinardi** [comment]
Please ignore the cost overview page - that's a copy and paste from the ABM discussion.  I want to complete a similar page for SWIM, but have not yet gotten to it yet - so all the of the information is for the ABM not SWIM - please ignore that page at this time.

My memory is that we agreed to just use Metro's assumptions for both auto and truck because that would allow us to be consistent with them, and Metro's values are close enough to ours that there is no real justification to be different.

I believe Joel's conversion from 2017 to 2010 should be correct.  
Please let me know if there are any further questions

**Comment by nsdhakar** [comment]
Made VOT updates to two procedure files:

- [initAutoAssignment.xml](https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/initAutoAssignment.xml) - now running two PrT assignment procedures (peak and offpeak). Prior to every assignment, AUTO_COST is re-calculated using VOT for the assignment period.
- [pathBasedAssignmentSettings_Full.xml](https://github.com/tlumip/tlumip/blob/master/root/scenario/model/code/visum/pathBasedAssignmentSettings_Full.xml) - now calculating AUTO_COST before every assignment to re-calculate AUTO_COST using VOT for the assignment period.

Here are the new COST equations:

TRUCK_COST = Floor(92.21*[TOLL_PRTSYS(D)]+11.07*[LENGTH]) 
AUTO_COST (Peak) = Floor(186.63*[TOLL_PRTSYS(A)]+22.40*[LENGTH])
AUTO_COST (Off Peak) = Floor(280.59*[TOLL_PRTSYS(A)]+33.67*[LENGTH]) 

Used Metro VOT assumptions (2010 dollars): $39.04 for trucks, $19.29 for auto peak, and $12.83 for auto off-peak. The calculations are based on [Link Impedance](https://github.com/tlumip/tlumip/wiki/Traffic-Assignment#link-impedance).

**Comment by bettinardi** [comment]
As I'm looking back at the page - https://github.com/tlumip/tlumip/wiki/Costs-Overview
I think you were right to question whether the model dollar year is 2010 or 2009.  @jfdman, can we get a more definitive statement on whether it's 2010 or 2009.  Looking back I think I did purposefully put 2009, on that page, indicating that maybe I tracked down information that suggested that 2009 was correct.

It looks like maybe I am working from NED - https://github.com/tlumip/tlumip/wiki/NED#ned-operation-in-swim

Which states:
All dollar values are expressed in 2009 base-year dollars, consistent with the rest of SWIM2

**Comment by bettinardi** [comment]
@nsdhakar - just from this from Joel from Dec 2018.  Looks like the 2010 should be adjusted one more year to 2009.  Can you see how big of a difference this makes to the files, and report back to this issue thread.

From Joel Dec 6th, 2018:
I feel like we have had conversations about year of cost and income in SWIM multiple times, and revised documents several times as well. The design doc clearly states that all costs and incomes are in 2009$

**Comment by jfdman** [comment]
Divide the 2010 VOTs by 1.03 to convert to 2009 VOTs

**Comment by RAKnudson** [comment]
Since 2010 is barely beyond the Great Recession, 3% deflator seemed high.

A convenient way to adjust for inflation is to use the Oregon Employment Departments Inflation Calculator tool:
https://www.qualityinfo.org/ed-icalc/?at=1&t1=1~2019~2019

This source indicates 2010 dollars should be deflated by 2% instead of 3%.


Becky Knudson || Senior Transportation Economist || TPAU || Phone: 503.986.4113 ||

**Comment by nsdhakar** [comment]
Ok, Applied a factor of 1.02 on 2010 VOTs. Updated cost calculations with VOTs in 2009 dollars. New cost calculations are:

TRUCK_COST = Floor(94.06*[TOLL_PRTSYS(D)]+11.29*[LENGTH])
AUTO_COST (Peak) = Floor(190.36*[TOLL_PRTSYS(A)]+22.84*[LENGTH])
AUTO_COST (Off Peak) = Floor(286.20*[TOLL_PRTSYS(A)]+34.34*[LENGTH])

Used Metro VOT assumptions (2009 dollars): $38.27/hr for trucks, $18.91/hr for auto peak, and $12.58/hr for auto off-peak.
