### ISSUE TITLE
Metro Case Select Link Issue

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#90]
From #59 which is getting closed, it seems like I recorded an issue where the Metro select link file is not properly pulling trips from the full set of trip records.  In addition to this there are notes to ensure that the SL_Summary table generate for multiple select link runs as well as for a single select link run (which it does).  So for this issue, I can provide the Metro file, it can be run checked and then we can also verify that the summary table generates correctly.  Lastly, a new field needs to be added to the summary table:

Add a “SDT_VEHICLE_TRIP” column to the SL_Summary file, where SDT is filtered down to just “DA”, “SR2” and “SR3P” on the tripMode, and then DA gets a value of 1, SR2 gets 0.5 and SR3P gets 0.3 and those values are summed so that the summary file can be used to compare to the auto vehicle trips on the link as well as the truck.

Here is the copied issue covering the Metro concern:

Currently (at least with the Metro example), the process litters the folder directory with a bunch of empty (just header) "sl_weaving..." files. We need to figure out why those are being created; if it is a problem; fix the problem if it exists; and then make sure that meaningless files are output to the directory.

Additionally, the "SL" matrices do not appear to add to the "_SL.ver" file in a multi-select link configuration (I thought they were supposed to if the setting was on.

In addition we still have an issue where the multi-select link process is not pulling the correct number of trips (the issue appears to be isolated to SDT, but all trips should be checked and verified). The primary issue is to get the process working; the three sets of comments above our secondary.

The issue has specifically been seen in the Metro boundary select link file - others may follow.

**Comment by nsdhakar** [comment]
Here is an update on this issue:

- There was a bug in the select link weaving process that identifies sequence of links. Also, the two time periods were converted to four time periods at some point in the development of SWIM. However, the Java code was not updated to account for the four time periods. Fixed the Java code to read all four time periods. The two fixes eliminated weaving errors.
- The SL matrices are being added to the SL version file for both SL analysis (single link and multi-link or sub-area)
- Multi-link SL process was producing fewer records in LDT person file than LDT vehicle file. Fixed the Java code and now, as expected, we have more records in the LDT person file.
- Added SL summary table output to multi-link analysis as well

**Comment by bettinardi** [comment]
I like the improvements to the sl_summary.csv file.  One requested change -
In the run I just completed, there was no order to the rows that I could see.  Is it possible to order (sort) the rows by external station number, In/Out, and then period (assign class - could we change this name to period) before exporting?
