### ISSUE TITLE
swimr - investigate issues in percent difference calculations

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#93]
A handful of errors have been identified in the swimR functions (specifically the inconsistent treatment of calculating the percent difference for tables like pop, employment and VMT - VMT seems to incorrectly reference the base year, while Pop and Employment) correct reference the comparison scenario year).

**Comment by bettinardi** [comment]
I'll follow-up with some screenshots in an email, but I believe the issue is in yearly_summary lines 98, 112, 158 of - https://github.com/tlumip/swimr/blob/master/inst/rmarkdown/templates/compare_scenario/skeleton/skeleton.Rmd

**Comment by landisrm** [comment]
I believe this issue is resolved with https://github.com/tlumip/swimr/pull/32
